apiVersion: v1
kind: Service
metadata:
  name: guestbook-svc
  labels:
    app: guestbook
    tier: frontend
spec:
  type: NodePort
  selector:
    app: guestbook
    tier: frontend
  ports:
  - port: 8080 
    targetPort: 8080

